config/routes.rb
Takeoutapp::Application.routes.draw do
=begin
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :roles

  match '/cart' => 'public/carts#show', :as => :current_cart

  match '/twilio/index' => 'twilio#index', :as => :twilios
  match '/twilio/call_customer' => 'twilio#call_customer',
    :as => :twilio_call_customer
  match '/twilio/notify_customer' => 'twilio#notify_customer',
    :as => :twilio_notify_customer
  match '/twilio/order_placed' => 'twilio#order_placed',
    :as => :twilio_order_placed
  match '/twilio/order_placed_recite' => 'twilio#order_placed_recite',
    :as => :twilio_order_placed_recite
  match '/twilio/confirm_order' => 'twilio#confirm_order',
    :as => :twilio_confirm_order
  match '/twilio/estimated_wait' => 'twilio#estimated_wait',
    :as => :twilio_estimated_wait
  match '/twilio/goodbye' => 'twilio#goodbye', :as => :twilio_goodbye
  match '/twilio/error' => 'twilio#error', :as => :twilio_error
  match '/twilio/restaurant_status' => 'twilio#restaurant_status',
    :as => :restaurant_status
  match '/twilio/customer_status' => 'twilio#customer_status',
    :as => :customer_status

  match '/orders/:id/status_update' => 'public/orders#status_update',
    :as => :order_status

  match '/404' => 'errors#four_zero_four', :as => :four_zero_four
  match '/422' => 'errors#four_two_two', :as => :four_two_two
  match '/500' => 'errors#five_zero_zero', :as => :five_zero_zero

  namespace :public do
    resources :restaurants
    resources :menus
    resources :menu_section_items
    match 'menu_item_option/select/:id/:line_item_id' => 'menu_item_options#select',
      :as => :select_menu_item_option
    match 'cart/delivery' => 'carts#delivery', :as => :cart_delivery
    match 'cart/update_delivery' => 'carts#update_delivery', :via => [:post],
      :as => :cart_update_delivery
    match 'cart/tip' => 'carts#tip', :as => :cart_tip
    match 'cart/update_tip' => 'carts#update_tip', :via => [:post],
      :as => :cart_update_tip
    resources :carts
    match 'orders/:year/:month/:day/:category' => 'orders#index', :defaults =>
      {:year => Time.now.year, :month => Time.now.month, :day => Time.now.day,
      :category => 'all'}, :via => [:get], :as => :view_orders
    match 'orders/:year/:month/:day/restaurant/:restaurant' => 'orders#restaurant_index',
      :defaults => {:year => Time.now.year, :month => Time.now.month,
      :day => Time.now.day, :category => 'restaurant'}, :via => [:get],
      :as => :orders_by_restaurant
    match 'orders/:year/:month/:day/customer/:customer' => 'orders#customer_index',
      :defaults => { :year => Time.now.year, :month => Time.now.month,
      :day => Time.now.day, :category => 'customer'}, :via => [:get],
      :as => :orders_by_customer
    match 'orders/success' => 'orders#success', :as => :order_success
    match 'orders/failure' => 'orders#failure', :as => :order_failure
    resources :orders
    match '/customer' => 'orders#show_customer', :as => :show_customer
    match '/restauraunt_orders' => 'orders#show_restaurant_orders',
      :as => :show_restaurant_orders
    resources :line_items
    match '/line_item_options/:id' => 'line_items#destroy_option',
      :as => :destroy_line_item_option
    match 'delivery_address/:id' => 'delivery_addresses#show',
      :via => [:get], :as => :delivery_address
    match 'delivery_address_distance' => 'delivery_addresses#distance',
      :via => [:get], :as => :delivery_address_distance
    match 'delivery_address_distance' => 'delivery_addresses#update_distance',
      :via => [:post], :as => :update_delivery_address_distance
  end

  match "admin" => "admin#index", :as => :admin
  namespace :admin do
    resources :users
    resources :sales_offices
    resources :sales_people
    resources :cuisines
    match 'restaurants/import_csv' => 'restaurants#import_csv',
      :as => :import_restaurants
    match 'restaurants/create_csv' => 'restaurants#create_csv',
      :as => :create_restaurants
    resources :restaurants
    match 'restaurant/:id/location/new' => 'locations#new',
      :as => :restaurant_new_location
    match 'restaurant/:id/location/create' => 'locations#create',
      :as => :restaurant_create_location
    resources :locations
    match 'location/:id/menu/new' => 'menus#new', :as => :location_new_menu
    match 'location/:id/menu/create' => 'menus#create',
      :as => :location_create_menu
    match 'location/:id/menus/import_csv' => 'menus#import_csv',
      :as => :import_menus
    match 'location/:id/menus/create_csv' => 'menus#create_csv',
      :as => :create_menus
    resources :menus
    match 'menu/:id/menu_section/new' => 'menu_sections#new',
      :as => :menu_new_menu_section
    match 'menu/:id/menu_section/create' => 'menu_sections#create',
      :as => :menu_create_menu_section
    resources :menu_sections
    match 'menu_section/:id/menu_section_item/new' => 'menu_section_items#new',
      :as => :menu_section_new_menu_section_item
    match 'menu_section/:id/menu_section_item/create' => 'menu_section_items#create',
      :as => :menu_section_create_menu_section_item
    resources :menu_section_items
    match 'menu_section_item/:id/item_option_sections/new' => 'item_option_sections#new',
      :as => :menu_section_item_new_item_option_section
    match 'menu_section_item/:id/item_option_sections/create' => 'item_option_sections#create',
      :as => :menu_section_item_create_item_option_section
    resources :item_option_sections
    match 'item_option_sections/menu/:menu_id' => "item_option_sections#index_by_menu",
      :as => :item_option_sections_by_menu
    match 'item_option_section/:id/menu_item_options/new' => 'menu_item_options#new',
      :as => :item_option_section_new_menu_item_option
    match 'item_option_section/:id/menu_item_options/create' => 'menu_item_options#create',
      :as => :item_option_section_create_menu_item_option
    resources :menu_item_options
    match 'orders/:year/:month/:day/:category' => 'orders#index',
      :defaults => {:year => Time.now.year, :month => Time.now.month,
      :day => Time.now.day, :category => 'all'}, :via => [:get],
      :as => :view_orders
    match 'orders/:year/:month/:day/restaurant/:restaurant' => 'orders#restaurant_index',
      :defaults => {:year => Time.now.year, :month => Time.now.month,
      :day => Time.now.day, :category => 'restaurant'}, :via => [:get],
      :as => :orders_by_restaurant
    match 'orders/:year/:month/:day/customer/:customer' => 'orders#customer_index',
      :defaults => {:year => Time.now.year, :month => Time.now.month,
      :day => Time.now.day, :category => 'customer'}, :via => [:get],
      :as => :orders_by_customer
    match 'orders/incomplete' => 'orders#incomplete_orders',
      :as => :incomplete_orders
    match 'orders/complete' => 'orders#complete_orders',
      :as => :complete_orders
    match 'orders/:id/update_status' => 'orders#update_status',
      :as => :update_order_status
    resources :orders
    match '/customer' => 'orders#show_customer', :as => :show_customer
    match '/restauraunt_orders' => 'orders#show_restaurant_orders',
      :as => :show_restaurant_orders
    resources :delivery_drivers
    resources :delivery_hours
    resources :printers
    match '/batches/drivers' => 'batches#drivers', :as => :batches_drivers
    resources :batches
    match '/clock_in' => "clock_in#create", :as => :clock_in
    match '/clock_out' => "clock_in#destroy", :as => :clock_out
  end

  match 'about' => 'information#about', :as => :about
  match 'faq' => 'information#faq', :as => :faq
  match 'privacy' => 'information#privacy', :as => :privacy
  match 'terms' => 'information#terms', :as => :terms
  match 'about_delivery' => 'information#delivery', :as => :about_delivery
  match 'promote_restaurant' => 'information#restaurant',
    :as => :promote_restaurant

  resources :contacts

  get "welcome/index"
  root :to => 'welcome#index'
=end

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :sales_office
  has_and_belongs_to_many :users
  has_and_belongs_to_many :delivery_drivers
  has_many :restaurant_hours, :dependent => :destroy
  has_many :holidays, :dependent => :destroy
  has_many :menus, :dependent => :destroy
  has_many :location_numbers, :dependent => :destroy
  has_one :delivery
  has_one :printer
  has_one :sales_person

  attr_accessor :delivers

  accepts_nested_attributes_for :restaurant_hours, :allow_destroy => true
  accepts_nested_attributes_for :holidays, :allow_destroy => true
  accepts_nested_attributes_for :delivery, :allow_destroy => true
  accepts_nested_attributes_for :location_numbers, :reject_if => :all_blank,
    :allow_destroy => true

  validates :address, :presence => true, :length => { :in => 1..250 }
  validates :region, :presence => true, :length => { :in => 1..100 }
  validates :city, :presence => true, :length => { :in => 1..150 }
=begin
  validates :phone, :presence => true, :length => { :in => 1..50 },
    :format => { :with => /^(1?(-?\d{3})-?)?(\d{3})(-?\d{4})$/ }
  validates :send_digits_ext, :length => { :in => 1..20 }, :allow_blank => true
  validates :txt_no, :length => { :in => 1..50 }, :allow_blank => true,
    :format => { :with => /^(1?(-?\d{3})-?)?(\d{3})(-?\d{4})$/ }
=end
  #validates_associated :restaurant, :restaurant_hours, :holidays, :menus
  validates_associated :delivery, :restaurant_hours, :holidays, :users,
    :location_numbers

  def full_address
    "#{self.address}, #{self.city}, #{self.region}"
  end

  def restaurant_name
    self.restaurant.name
  end

  def delivers
    if self.delivery
      return true
    else
      return false
    end
  end

  def self.delivers
    if delivery
      return true
    else
      return false
    end
  end

  def drivers_active?
    @delivering = false
    delivery_drivers.each do |delivery_driver|
      if delivery_driver.is_delivering?
        @delivering = true
      end
    end
    return @delivering
  end

  def delivery_fee
    delivery.fee
  end

  def main_phone_number
    @location_number = LocationNumber.where(:location_id => id, :main_number => true).first
    return @location_number.phone
  end

  def main_digits_ext
    @location_number = LocationNumber.where(:location_id => id, :main_number => true).first
    if @location_number.send_digits_ext
      ext_digits = @location_number.send_digits_ext
    end
    return ext_digits
  end

  def sends_digits_ext
    @location_numbers = LocationNumber.where(:location_id => id, :text_number => false)
    if !@location_numbers.first.send_digits_ext.blank?
      return true
    else
      return false
    end
  end

  def on_holiday?
    @holiday = false
    if holidays && holidays.length > 0
      holidays.each do |holiday|
        if holiday.is_holiday?
          @holiday = true
        end
      end
    end
    return @holiday
  end
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < AdminController
  load_and_authorize_resource
  #before_filter :user_collection, :only => [:new, :create, :edit, :update]
  before_filter :sales_person_collection, :only => [:new, :create, :edit, :update]
  before_filter :driver_collection, :only => [:new, :create, :edit, :update]

  def show
    @location = Location.find(params[:id])
    @restaurant = @location.restaurant
  end

  def new
    @location = Location.new
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @location = Location.new(params[:location])
    @restaurant = Restaurant.find(params[:id])
    @location.restaurant = @restaurant

    if @location.save
      redirect_to admin_restaurant_path(@restaurant), :notice => 'Location added.'
    else
      redirect_to admin_restaurant_new_location_path(@location.restaurant), :alert => 'Add location failed.'
    end
  end

  def edit
    @location = Location.find(params[:id])
    @restaurant = @location.restaurant
    @submit_name = "Edit location"
  end

  def update
    params[:location][:user_ids] ||= []
    params[:location][:delivery_driver_ids] ||= []
    @location = Location.find(params[:id])

    if @location.update_attributes(params[:location])
      redirect_to admin_location_path(@location), :notice => "Location updated."
    else
      redirect_to edit_admin_location_path(@location), :alert => "Location update failed."
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @restaurant = @location.restaurant
    @location.destroy
    redirect_to admin_restaurant_path(@restaurant)
  end

  protected

    def user_collection
      #@user_collection = User.where("role = ?", "admin")
      @user_collection = User.where(:role => ["admin", "restaurant_owner", "restaurant_editor"])
    end

    def sales_person_collection
      @sales_person_collection = SalesPerson.all.collect {|sp| [sp.user.email, sp.id]}
    end

    def driver_collection
      @driver_collection = DeliveryDriver.joins(:user)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
  def states_array
    [
      ["Texas", "TX"]
    ].freeze
  end
end

app/views/admin/locations/_delivery_fields.html.haml
%span.fields
  %li
    = f.label :fee, "Deliver fee"
    = f.text_field :fee
  %li
    %ol
      %li
        - @driver_collection.each do |driver|
          %li.check.collection
            = check_box_tag "location[delivery_driver_ids][]", driver.id, @location.delivery_drivers.include?(driver)
            = driver.user.email
        %br
  %li
    = link_to_remove_fields "remove delivery", f

app/views/admin/locations/_form.html.haml
= form_for location, :url => theurl do |loc_f|
  = render "/shared/error_messages", :target => @location
  %fieldset
    %legend
      Location for #{@restaurant.name}
    %ol
      %li.check
        = loc_f.label :active, "Location Active"
        = loc_f.check_box :active
        <br />
      %li
        = loc_f.label :address
        = loc_f.text_field :address
      %li
        = loc_f.label :city
        = loc_f.text_field :city
      %li
        = loc_f.label :region, "State"
        = loc_f.select :region, states_array, :include_blank => true
      %li
        = loc_f.label :postal_code
        = loc_f.text_field :postal_code
      %li
        = loc_f.label :lat, "Latitude"
        = loc_f.text_field :lat
      %li
        = loc_f.label :lon, "Longitude"
        = loc_f.text_field :lon
      %li
        = loc_f.label :email, "Email"
        = loc_f.text_field :email
      %li
        = loc_f.label :percentage, "Sale Percentage"
        = loc_f.text_field :percentage
      %li.check
        = loc_f.label :recite_order, "Recite order in phone notification"
        = loc_f.check_box :recite_order
        <br />
  %fieldset
    %legend Phone Numbers
    %ol
      = loc_f.fields_for :location_numbers do |builder|
        = render 'location_number_fields', :f => builder
      %li.add_fields= link_to_add_fields "Add Phone Numbers", loc_f, :location_numbers
  %fieldset
    %legend Delivery
    %ol
      = loc_f.fields_for :delivery do |builder|
        = render 'delivery_fields', :f => builder
      %li.add_fields= link_to_add_fields "Add Restaurant Delivery", loc_f, :delivery
  %fieldset
    %legend Hours
    %ol
      = loc_f.fields_for :restaurant_hours do |builder|
        = render 'restaurant_hour_fields', :f => builder
      %li.add_fields= link_to_add_fields "Add Restaurant Hours", loc_f, :restaurant_hours
  %fieldset
    %legend Holidays
    %ol
      = loc_f.fields_for :holidays do |builder|
        = render 'holiday_fields', :f => builder
      %li.add_fields= link_to_add_fields "Add Holidays", loc_f, :holidays
  - if current_user.role? :admin
    %fieldset
      %legend Sales Person
      %ol
        %li
          = loc_f.label :sales_person
          = loc_f.select :sales_person_id, @sales_person_collection, {:prompt => "Choose sales person"}
    -#%fieldset
    -#  %legend Users
    -#  %ol
    -#    %li
    -#      %ol
    -#        - @user_collection.each do |user|
    -#          %li.check.collection
    -#            = check_box_tag "location[user_ids][]", user.id, @location.users.include?(user)
    -#            = user.email
    -#        %br
  %fieldset
    %p= loc_f.submit @submit_name

app/views/admin/locations/_holiday_fields.html.haml
%span.fields
  %li.check
    = f.label :all_day, "All day?"
    = f.check_box :all_day
    %br/
  %li
    = f.label :start_hr, "Opens"
    = f.select :start_hr, 0..23, {:prompt => "Choose hour"}
    \:
    \#{f.select :start_min, (00..59).step(5)}
  %li
    = f.label :end_hr, "Closes"
    = f.select :end_hr, 0..23, {:prompt => "Choose hour"}
    \:
    \#{f.select :end_min, (00..59).step(5)}
  %li
    = f.label :day
    = f.date_select :day, :discard_year => true
  %li
    = link_to_remove_fields "remove", f

app/views/admin/locations/_location_number_fields.html.haml
%span.fields
  %li
    = f.label :phone, "Phone Number"
    = f.text_field :phone
  %li
    = f.label :send_digits_ext, "Extension/Extra Phone Digits"
    = f.text_field :send_digits_ext
  %li.check
    = f.label :main_number, "Is Main Number?"
    = f.check_box :main_number
    <br />
  %li.check
    = f.label :text_number, "Is Text Number?"
    = f.check_box :text_number
    <br />
  %li
    = link_to_remove_fields "remove phone number", f

app/views/admin/locations/_restaurant_hour_fields.html.haml
%span.fields
  %li
    = f.label :day, "Day"
    = f.select :day, days_array
  %li
    = f.label :start_hr, "Opens"
    = f.select :start_hr, 0..23, {:prompt => "Choose hour"}
    \:
    \#{f.select :start_min, (00..59).step(5)}
  %li
    = f.label :end_hr, "Closes"
    = f.select :end_hr, 0..23, {:prompt => "Choose hour"}
    \:
    \#{f.select :end_min, (00..59).step(5)}
  %li
    = link_to_remove_fields "remove", f

app/views/admin/locations/edit.html.haml
%h1
  Edit Location for #{@location.restaurant.name}
= render :partial => "form", :locals => {:location => @location, :theurl => admin_location_path(@location, :method => "post")}

app/views/admin/locations/new.html.haml
%h1
  Add Location for #{@restaurant.name}
= render :partial => "form", :locals => {:location => @location, :theurl => admin_restaurant_create_location_path(@restaurant)}

app/views/admin/locations/show.html.haml
- content_for :crumbs do
  %ul
    %li
      = link_to "Admin Home", admin_path
      \&raquo; #{link_to "Restaurants", admin_restaurants_path} &raquo; #{link_to "Restaurant", admin_restaurant_path(@location.restaurant)}
%h1= h @restaurant.name
%h2
  = h @location.address
  , #{h @location.city}, #{h @location.region} #{h @location.postal_code}
%p
  = link_to "Add menu", admin_location_new_menu_path(@location)
  | #{link_to "Import menu csv", admin_import_menus_path(@location)}
- if @location.restaurant_hours && @location.restaurant_hours.count > 0
  %h2 Hours
  %table
    %tr
      %th Day
      %th Open
      %th Close
    - @location.restaurant_hours.order("day ASC").each do |hour|
      %tr
        %td= h days_array[hour.day][0]
        %td= h to_ampm(hour.start_hr, hour.start_min)
        %td= h to_ampm(hour.end_hr, hour.end_min)
- if @location.holidays && @location.holidays.count > 0
  %h2 Holidays
  %table
    %tr
      %th Day
      %th All day?
      %th Open
      %th Close
    - @location.holidays.order("day ASC").each do |hour|
      %tr
        %td= h hour.day
        %td= h hour.all_day
        %td= h (hour.start_hr && hour.start_min) ? to_ampm(hour.start_hr, hour.start_min) : "Not set"
        %td= h (hour.end_hr && hour.end_min) ? to_ampm(hour.end_hr, hour.end_min) : "Not set"
%h2 Menus
%table
  %tr
    %th{:colspan => "2"} Menu
  - for menu in @location.menus.order("position ASC, created_at DESC") do
    %tr
      %td= link_to menu.name, admin_menu_path(menu)
      %td{:align => "right"}
        = link_to "Edit", edit_admin_menu_path(menu)
        | #{link_to "Destroy", admin_menu_path(menu), :method => "delete", :confirm => "Are you sure? This will remove the menu and all it's items."}
- if @location.users && @location.users.length > 0
  %h2 Users
  %ul
    - @location.users.each do |user|
      %li= user.email
%h2 Printers
%ul
  - if @location.printer
    %li
      #{@location.printer.model_name} #{@location.printer.service_no}
      | #{link_to "Edit Printer", edit_admin_printer_path(@location.printer)}
      | #{link_to "Destroy Printer", admin_printer_path(@location.printer), :method => "delete", :confirm => "Are you sure? This cannot be undone."}
  %li= link_to "Add Printer", new_admin_printer_path