config/routes.rb
Takeoutapp::Application.routes.draw do
=begin
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :roles

  match '/cart' => 'public/carts#show', :as => :current_cart

  match '/twilio/index' => 'twilio#index', :as => :twilios
  match '/twilio/call_customer' => 'twilio#call_customer',
    :as => :twilio_call_customer
  match '/twilio/notify_customer' => 'twilio#notify_customer',
    :as => :twilio_notify_customer
  match '/twilio/order_placed' => 'twilio#order_placed',
    :as => :twilio_order_placed
  match '/twilio/order_placed_recite' => 'twilio#order_placed_recite',
    :as => :twilio_order_placed_recite
  match '/twilio/confirm_order' => 'twilio#confirm_order',
    :as => :twilio_confirm_order
  match '/twilio/estimated_wait' => 'twilio#estimated_wait',
    :as => :twilio_estimated_wait
  match '/twilio/goodbye' => 'twilio#goodbye', :as => :twilio_goodbye
  match '/twilio/error' => 'twilio#error', :as => :twilio_error
  match '/twilio/restaurant_status' => 'twilio#restaurant_status',
    :as => :restaurant_status
  match '/twilio/customer_status' => 'twilio#customer_status',
    :as => :customer_status

  match '/orders/:id/status_update' => 'public/orders#status_update',
    :as => :order_status

  match '/404' => 'errors#four_zero_four', :as => :four_zero_four
  match '/422' => 'errors#four_two_two', :as => :four_two_two
  match '/500' => 'errors#five_zero_zero', :as => :five_zero_zero

  namespace :public do
    resources :restaurants
    resources :menus
    resources :menu_section_items
    match 'menu_item_option/select/:id/:line_item_id' => 'menu_item_options#select',
      :as => :select_menu_item_option
    match 'cart/delivery' => 'carts#delivery', :as => :cart_delivery
    match 'cart/update_delivery' => 'carts#update_delivery', :via => [:post],
      :as => :cart_update_delivery
    match 'cart/tip' => 'carts#tip', :as => :cart_tip
    match 'cart/update_tip' => 'carts#update_tip', :via => [:post],
      :as => :cart_update_tip
    resources :carts
    match 'orders/:year/:month/:day/:category' => 'orders#index', :defaults =>
      {:year => Time.now.year, :month => Time.now.month, :day => Time.now.day,
      :category => 'all'}, :via => [:get], :as => :view_orders
    match 'orders/:year/:month/:day/restaurant/:restaurant' => 'orders#restaurant_index',
      :defaults => {:year => Time.now.year, :month => Time.now.month,
      :day => Time.now.day, :category => 'restaurant'}, :via => [:get],
      :as => :orders_by_restaurant
    match 'orders/:year/:month/:day/customer/:customer' => 'orders#customer_index',
      :defaults => { :year => Time.now.year, :month => Time.now.month,
      :day => Time.now.day, :category => 'customer'}, :via => [:get],
      :as => :orders_by_customer
    match 'orders/success' => 'orders#success', :as => :order_success
    match 'orders/failure' => 'orders#failure', :as => :order_failure
    resources :orders
    match '/customer' => 'orders#show_customer', :as => :show_customer
    match '/restauraunt_orders' => 'orders#show_restaurant_orders',
      :as => :show_restaurant_orders
    resources :line_items
    match '/line_item_options/:id' => 'line_items#destroy_option',
      :as => :destroy_line_item_option
    match 'delivery_address/:id' => 'delivery_addresses#show',
      :via => [:get], :as => :delivery_address
    match 'delivery_address_distance' => 'delivery_addresses#distance',
      :via => [:get], :as => :delivery_address_distance
    match 'delivery_address_distance' => 'delivery_addresses#update_distance',
      :via => [:post], :as => :update_delivery_address_distance
  end

  match "admin" => "admin#index", :as => :admin
  namespace :admin do
    resources :users
    resources :sales_offices
    resources :sales_people
    resources :cuisines
    match 'restaurants/import_csv' => 'restaurants#import_csv',
      :as => :import_restaurants
    match 'restaurants/create_csv' => 'restaurants#create_csv',
      :as => :create_restaurants
    resources :restaurants
    match 'restaurant/:id/location/new' => 'locations#new',
      :as => :restaurant_new_location
    match 'restaurant/:id/location/create' => 'locations#create',
      :as => :restaurant_create_location
    resources :locations
    match 'location/:id/menu/new' => 'menus#new', :as => :location_new_menu
    match 'location/:id/menu/create' => 'menus#create',
      :as => :location_create_menu
    match 'location/:id/menus/import_csv' => 'menus#import_csv',
      :as => :import_menus
    match 'location/:id/menus/create_csv' => 'menus#create_csv',
      :as => :create_menus
    resources :menus
    match 'menu/:id/menu_section/new' => 'menu_sections#new',
      :as => :menu_new_menu_section
    match 'menu/:id/menu_section/create' => 'menu_sections#create',
      :as => :menu_create_menu_section
    resources :menu_sections
    match 'menu_section/:id/menu_section_item/new' => 'menu_section_items#new',
      :as => :menu_section_new_menu_section_item
    match 'menu_section/:id/menu_section_item/create' => 'menu_section_items#create',
      :as => :menu_section_create_menu_section_item
    resources :menu_section_items
    match 'menu_section_item/:id/item_option_sections/new' => 'item_option_sections#new',
      :as => :menu_section_item_new_item_option_section
    match 'menu_section_item/:id/item_option_sections/create' => 'item_option_sections#create',
      :as => :menu_section_item_create_item_option_section
    resources :item_option_sections
    match 'item_option_sections/menu/:menu_id' => "item_option_sections#index_by_menu",
      :as => :item_option_sections_by_menu
    match 'item_option_section/:id/menu_item_options/new' => 'menu_item_options#new',
      :as => :item_option_section_new_menu_item_option
    match 'item_option_section/:id/menu_item_options/create' => 'menu_item_options#create',
      :as => :item_option_section_create_menu_item_option
    resources :menu_item_options
    match 'orders/:year/:month/:day/:category' => 'orders#index',
      :defaults => {:year => Time.now.year, :month => Time.now.month,
      :day => Time.now.day, :category => 'all'}, :via => [:get],
      :as => :view_orders
    match 'orders/:year/:month/:day/restaurant/:restaurant' => 'orders#restaurant_index',
      :defaults => {:year => Time.now.year, :month => Time.now.month,
      :day => Time.now.day, :category => 'restaurant'}, :via => [:get],
      :as => :orders_by_restaurant
    match 'orders/:year/:month/:day/customer/:customer' => 'orders#customer_index',
      :defaults => {:year => Time.now.year, :month => Time.now.month,
      :day => Time.now.day, :category => 'customer'}, :via => [:get],
      :as => :orders_by_customer
    match 'orders/incomplete' => 'orders#incomplete_orders',
      :as => :incomplete_orders
    match 'orders/complete' => 'orders#complete_orders',
      :as => :complete_orders
    match 'orders/:id/update_status' => 'orders#update_status',
      :as => :update_order_status
    resources :orders
    match '/customer' => 'orders#show_customer', :as => :show_customer
    match '/restauraunt_orders' => 'orders#show_restaurant_orders',
      :as => :show_restaurant_orders
    resources :delivery_drivers
    resources :delivery_hours
    resources :printers
    match '/batches/drivers' => 'batches#drivers', :as => :batches_drivers
    resources :batches
    match '/clock_in' => "clock_in#create", :as => :clock_in
    match '/clock_out' => "clock_in#destroy", :as => :clock_out
  end

  match 'about' => 'information#about', :as => :about
  match 'faq' => 'information#faq', :as => :faq
  match 'privacy' => 'information#privacy', :as => :privacy
  match 'terms' => 'information#terms', :as => :terms
  match 'about_delivery' => 'information#delivery', :as => :about_delivery
  match 'promote_restaurant' => 'information#restaurant',
    :as => :promote_restaurant

  resources :contacts

  get "welcome/index"
  root :to => 'welcome#index'
=end

end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  skip_before_filter :authenticate_user!

  def about
  end

  def faq
  end

  def delivery
    @restaurants = Restaurant.joins(:locations => :delivery).where("locations.active = ? AND restaurants.id != ?", true, 11)
  end

  def restaurant
  end

  def privacy
  end

  def terms
  end
end

app/views/information/about.html.haml
%h1 This Is ChowBrowser
%p There’s a lot of good people making a lot of good food. We aim to make good food easy to find and convenient to order. We’re connecting great restaurants with their happy customers.
%p The ChowBrowser application has the sole purpose of keeping you fed and happy. If we didn’t think a feature would make your life easier we didn’t include it. It’s simple, it’s quick, cheers all around.
%em Choose a restaurant, place an order, checkout, rock on.
%h2 Promote Your Restaurant
%p We’d love to work with your restaurant and provide you with the ability to take online orders.

app/views/information/delivery.html.haml
- content_for :other_styles do
  = stylesheet_link_tag 'public/restaurants'
%section.one
  %div
    %h1 Appetizing and Accomodating
    %p ChowBrowser values convenience. Not up for going out? We&rsquo;ll deliver the dining out experience to you. When we are offering delivery you&rsquo;ll have the option for your order to be delivered at the small additional fee of $2.99.
    %p Delivery orders are usually completed within 30 minutes to an hour. It generally takes around 20 minutes to prepare a meal and 10 to 20 minutes to deliver it from the restaurant to you. Of course, this can vary depending on traffic conditions and the distance from the restaurant to you. A more approximate estimate is displayed to you upon completion of your order.
    %p Delivery is limited to a 10 mile radius surrounding a restaurant to ensure your food reaches you fresh and at the intended temperature.
%h2{:style => "margin:35px 0 0;font-family:'Salsa',serif;color:#fff;text-align:center;padding:10px;background-color:#002f5c;"} Now Offering Delivery From The Following
%ul#restaurants_list.cf{:style => "margin-top: 35px;"}
  - for restaurant in @restaurants do
    - for location in restaurant.locations do
      - if location.menus.exists?
        %li
          - current_menu = which_menu?(location.menus)
          - if current_menu.nil?
            - current_menu = location.menus.order("position ASC, created_at DESC").first
          %h1= link_to restaurant.name, public_menu_path(current_menu.id)
          %p
            = location.address
            , #{location.city}, #{location.region} #{location.postal_code}

app/views/information/faq.html.haml
%h1 Q&A
%dl
  %dt
  %dd
%p
  Have a question? #{link_to "Contact us", new_contact_path}.

app/views/information/privacy.html.haml
- content_for :other_styles do
  = stylesheet_link_tag 'information'
%section.one
  %div
    %h1 Privacy Policy
    %p Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. The following outlines our privacy policy.
    %ul
      %li Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.
      %li We will collect and use of personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law.
      %li We will only retain personal information as long as necessary for the fulfillment of those purposes.
      %li We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned.
      %li Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date.
      %li We will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.
      %li We will make readily available to customers information about our policies and practices relating to the management of personal information.
    %p We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained.

app/views/information/restaurant.html.haml
%section.one
  %div
    %h1 Put ChowBrowser To Work For Your Restaurant
    %p ChowBrowser would like to join your restaurant. We’ve got customers and want to bring them to you. #{link_to "Contact us", new_contact_path} for more information.

app/views/information/terms.html.haml
- content_for :other_styles do
  = stylesheet_link_tag 'information'
%section.one
  %div
    %p ChowBrowser, llc. (“ChowBrowser”) operates the website located at chowbrowser.com (the “Site”)
    %h1 Web Site Terms and Conditions of Use
    %ol
      %li
        %h2 Terms
        %p By accessing the Site, you are agreeing to be bound by these Web Site Terms and Conditions of Use, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. The term “you” or “You” shall refer to any person or entity who views, uses, accesses, browses or submits any content or material to the site. The materials contained in the Site are protected by applicable copyright and trade mark law.
        %p If you do not agree with any of these terms, you are prohibited from using or accessing the Site. ChowBrowser reserves the right to modify these Terms of Use at any time without prior notice.
      %li
        %h2 Use License
        %ol
          %li
            ChowBrowser grants you permission (which may be revoked at any time for any reason) to view the Site and to download, email, share through social networking or print individual pages from the Site for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:
            %ol
              %li access the Site or services using a third-party’s account/registration without the express consent of the account holder;
              %li use the Site for illegal purposes;
              %li use the Site to engage in commercial activities apart from sanctioned use of ChowBrowser services;
              %li attempt to gain unauthorized access to other computer systems from or through the Site;
              %li upload or transmit viruses or other harmful, disruptive or destructive files;
              %li disrupt, interfere with, or otherwise harm or violate the security of the Site, or any services, system resources, accounts, passwords, servers or networks connected to or accessible through the Site or affiliated or linked sites (including those of our restaurant partners);
              %li modify or copy the materials;
              %li use the materials for any commercial purpose, or for any public display (commercial or non-commercial);
              %li attempt to decompile or reverse engineer any software contained on ChowBrowser’s web site;
              %li remove any copyright or other proprietary notations from the materials; or
              %li transfer the materials to another person or "mirror" the materials on any other server.
          %li This license shall automatically terminate if you violate any of these restrictions and may be terminated by ChowBrowser at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.
      %li
        %h2 Disclaimer
        %ol
          %li The materials on ChowBrowser's web site are provided "as is". ChowBrowser makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, ChowBrowser does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.
      %li
        %h2 Limitations
        %p In no event shall ChowBrowser or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on ChowBrowser's Internet site, even if ChowBrowser or a ChowBrowser authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
      %li
        %h2 Your Account, Password and Security
        %p You are responsible for maintaining the confidentiality and security of your Account and password, and you are fully responsible for all activities that occur under your password or Account, and for any other actions taken in connection with the Account or password. You agree to (a) immediately notify ChowBrowser of any known or suspected unauthorized use(s) of your password or Account, or any known or suspected breach of security, including loss, theft, or unauthorized disclosure of your password or credit card information; and (b) ensure that you exit from your Account at the end of each session. ChowBrowser will not be liable for any injury, loss or damage of any kind arising from or relating to your failure to comply with (a) and (b) or for any acts or omissions by you or someone else using your Account and/or password.
      %li
        %h2 Revisions and Errata
        %p The materials appearing on ChowBrowser's web site could include technical, typographical, or photographic errors. ChowBrowser does not warrant that any of the materials on its web site are accurate, complete, or current. ChowBrowser may make changes to the materials contained on its web site at any time without notice. ChowBrowser does not, however, make any commitment to update the materials.
      %li
        %h2 Links
        %p ChowBrowser has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by ChowBrowser of the site. Use of any such linked web site is at the user's own risk.
      %li
        %h2 Site Terms of Use Modifications
        %p ChowBrowser may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.
      %li
        %h2 Governing Law
        %p Any claim relating to ChowBrowser's web site shall be governed by the laws of the State of Texas without regard to its conflict of law provisions.
        %p General Terms and Conditions applicable to Use of a Web Site.