config/routes.rb
Takeoutapp::Application.routes.draw do
=begin
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :roles

  match '/cart' => 'public/carts#show', :as => :current_cart

  match '/twilio/index' => 'twilio#index', :as => :twilios
  match '/twilio/call_customer' => 'twilio#call_customer',
    :as => :twilio_call_customer
  match '/twilio/notify_customer' => 'twilio#notify_customer',
    :as => :twilio_notify_customer
  match '/twilio/order_placed' => 'twilio#order_placed',
    :as => :twilio_order_placed
  match '/twilio/order_placed_recite' => 'twilio#order_placed_recite',
    :as => :twilio_order_placed_recite
  match '/twilio/confirm_order' => 'twilio#confirm_order',
    :as => :twilio_confirm_order
  match '/twilio/estimated_wait' => 'twilio#estimated_wait',
    :as => :twilio_estimated_wait
  match '/twilio/goodbye' => 'twilio#goodbye', :as => :twilio_goodbye
  match '/twilio/error' => 'twilio#error', :as => :twilio_error
  match '/twilio/restaurant_status' => 'twilio#restaurant_status',
    :as => :restaurant_status
  match '/twilio/customer_status' => 'twilio#customer_status',
    :as => :customer_status

  match '/orders/:id/status_update' => 'public/orders#status_update',
    :as => :order_status

  match '/404' => 'errors#four_zero_four', :as => :four_zero_four
  match '/422' => 'errors#four_two_two', :as => :four_two_two
  match '/500' => 'errors#five_zero_zero', :as => :five_zero_zero

  namespace :public do
    resources :restaurants
    resources :menus
    resources :menu_section_items
    match 'menu_item_option/select/:id/:line_item_id' => 'menu_item_options#select',
      :as => :select_menu_item_option
    match 'cart/delivery' => 'carts#delivery', :as => :cart_delivery
    match 'cart/update_delivery' => 'carts#update_delivery', :via => [:post],
      :as => :cart_update_delivery
    match 'cart/tip' => 'carts#tip', :as => :cart_tip
    match 'cart/update_tip' => 'carts#update_tip', :via => [:post],
      :as => :cart_update_tip
    resources :carts
    match 'orders/:year/:month/:day/:category' => 'orders#index', :defaults =>
      {:year => Time.now.year, :month => Time.now.month, :day => Time.now.day,
      :category => 'all'}, :via => [:get], :as => :view_orders
    match 'orders/:year/:month/:day/restaurant/:restaurant' => 'orders#restaurant_index',
      :defaults => {:year => Time.now.year, :month => Time.now.month,
      :day => Time.now.day, :category => 'restaurant'}, :via => [:get],
      :as => :orders_by_restaurant
    match 'orders/:year/:month/:day/customer/:customer' => 'orders#customer_index',
      :defaults => { :year => Time.now.year, :month => Time.now.month,
      :day => Time.now.day, :category => 'customer'}, :via => [:get],
      :as => :orders_by_customer
    match 'orders/success' => 'orders#success', :as => :order_success
    match 'orders/failure' => 'orders#failure', :as => :order_failure
    resources :orders
    match '/customer' => 'orders#show_customer', :as => :show_customer
    match '/restauraunt_orders' => 'orders#show_restaurant_orders',
      :as => :show_restaurant_orders
    resources :line_items
    match '/line_item_options/:id' => 'line_items#destroy_option',
      :as => :destroy_line_item_option
    match 'delivery_address/:id' => 'delivery_addresses#show',
      :via => [:get], :as => :delivery_address
    match 'delivery_address_distance' => 'delivery_addresses#distance',
      :via => [:get], :as => :delivery_address_distance
    match 'delivery_address_distance' => 'delivery_addresses#update_distance',
      :via => [:post], :as => :update_delivery_address_distance
  end

  match "admin" => "admin#index", :as => :admin
  namespace :admin do
    resources :users
    resources :sales_offices
    resources :sales_people
    resources :cuisines
    match 'restaurants/import_csv' => 'restaurants#import_csv',
      :as => :import_restaurants
    match 'restaurants/create_csv' => 'restaurants#create_csv',
      :as => :create_restaurants
    resources :restaurants
    match 'restaurant/:id/location/new' => 'locations#new',
      :as => :restaurant_new_location
    match 'restaurant/:id/location/create' => 'locations#create',
      :as => :restaurant_create_location
    resources :locations
    match 'location/:id/menu/new' => 'menus#new', :as => :location_new_menu
    match 'location/:id/menu/create' => 'menus#create',
      :as => :location_create_menu
    match 'location/:id/menus/import_csv' => 'menus#import_csv',
      :as => :import_menus
    match 'location/:id/menus/create_csv' => 'menus#create_csv',
      :as => :create_menus
    resources :menus
    match 'menu/:id/menu_section/new' => 'menu_sections#new',
      :as => :menu_new_menu_section
    match 'menu/:id/menu_section/create' => 'menu_sections#create',
      :as => :menu_create_menu_section
    resources :menu_sections
    match 'menu_section/:id/menu_section_item/new' => 'menu_section_items#new',
      :as => :menu_section_new_menu_section_item
    match 'menu_section/:id/menu_section_item/create' => 'menu_section_items#create',
      :as => :menu_section_create_menu_section_item
    resources :menu_section_items
    match 'menu_section_item/:id/item_option_sections/new' => 'item_option_sections#new',
      :as => :menu_section_item_new_item_option_section
    match 'menu_section_item/:id/item_option_sections/create' => 'item_option_sections#create',
      :as => :menu_section_item_create_item_option_section
    resources :item_option_sections
    match 'item_option_sections/menu/:menu_id' => "item_option_sections#index_by_menu",
      :as => :item_option_sections_by_menu
    match 'item_option_section/:id/menu_item_options/new' => 'menu_item_options#new',
      :as => :item_option_section_new_menu_item_option
    match 'item_option_section/:id/menu_item_options/create' => 'menu_item_options#create',
      :as => :item_option_section_create_menu_item_option
    resources :menu_item_options
    match 'orders/:year/:month/:day/:category' => 'orders#index',
      :defaults => {:year => Time.now.year, :month => Time.now.month,
      :day => Time.now.day, :category => 'all'}, :via => [:get],
      :as => :view_orders
    match 'orders/:year/:month/:day/restaurant/:restaurant' => 'orders#restaurant_index',
      :defaults => {:year => Time.now.year, :month => Time.now.month,
      :day => Time.now.day, :category => 'restaurant'}, :via => [:get],
      :as => :orders_by_restaurant
    match 'orders/:year/:month/:day/customer/:customer' => 'orders#customer_index',
      :defaults => {:year => Time.now.year, :month => Time.now.month,
      :day => Time.now.day, :category => 'customer'}, :via => [:get],
      :as => :orders_by_customer
    match 'orders/incomplete' => 'orders#incomplete_orders',
      :as => :incomplete_orders
    match 'orders/complete' => 'orders#complete_orders',
      :as => :complete_orders
    match 'orders/:id/update_status' => 'orders#update_status',
      :as => :update_order_status
    resources :orders
    match '/customer' => 'orders#show_customer', :as => :show_customer
    match '/restauraunt_orders' => 'orders#show_restaurant_orders',
      :as => :show_restaurant_orders
    resources :delivery_drivers
    resources :delivery_hours
    resources :printers
    match '/batches/drivers' => 'batches#drivers', :as => :batches_drivers
    resources :batches
    match '/clock_in' => "clock_in#create", :as => :clock_in
    match '/clock_out' => "clock_in#destroy", :as => :clock_out
  end

  match 'about' => 'information#about', :as => :about
  match 'faq' => 'information#faq', :as => :faq
  match 'privacy' => 'information#privacy', :as => :privacy
  match 'terms' => 'information#terms', :as => :terms
  match 'about_delivery' => 'information#delivery', :as => :about_delivery
  match 'promote_restaurant' => 'information#restaurant',
    :as => :promote_restaurant

  resources :contacts

  get "welcome/index"
  root :to => 'welcome#index'
=end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  load_and_authorize_resource
  helper_method :sort_column, :sort_direction
  before_filter :get_params, :only => [:index, :restaurant_index, :customer_index]

  def index
    if current_user.role?(:admin)
      @purchased_collection = Order.year_collection.order("purchased_at_year ASC")
      if @year == "all"
        @orders = Order.joins(:cart).purchased.order("purchased_at DESC")
      else
        if @month == "all"
          @orders = Order.joins(:cart).by_year(@year).order("purchased_at DESC")
        else
          @orders = Order.joins(:cart).by_month_and_year(@month, @year).order("purchased_at DESC")
          if @day == "all"
            @orders = Order.joins(:cart).by_month_and_year(@month, @year).order("purchased_at DESC")
          else
            @orders = Order.joins(:cart).by_day(@month, @year, @day).order("purchased_at DESC")
          end
          @purchased_day_collection = Order.day_collection(@month, @year).order("purchased_at_day ASC")
        end
        @purchased_month_collection = Order.month_collection(@year).order("purchased_at_month ASC")
      end
      @order_months = @orders.group_by { |o| o.cart.purchased_at.beginning_of_month }
    elsif current_user.role?(:restaurant_owner) || current_user.role?(:restaurant_editor)
      @user_restaurants = current_user.restaurants
      @user_restaurants_ids = @user_restaurants.collect {|ursids| ursids.id}
      @purchased_collection = Order.select("DISTINCT extract(year from carts.purchased_at) AS
        purchased_at_year").restaurants_join(@user_restaurants_ids).purchased.order("purchased_at_year ASC")
      if @year == "all"
        @orders = Order.restaurants_join(@user_restaurants_ids).purchased.order("purchased_at DESC")
      else
        if @month == "all"
          @orders = Order.restaurants_join(@user_restaurants_ids).by_year(@year).order("purchased_at DESC")
        else
          @orders = Order.restaurants_join(@user_restaurants_ids).by_month_and_year(@month, @year).order("purchased_at DESC")
          if @day == "all"
            @orders = Order.restaurants_join(@user_restaurants_ids).by_month_and_year(@month, @year).order("purchased_at DESC")
          else
            @orders = Order.restaurants_join(@user_restaurants_ids).by_day(@month, @year, @day).order("purchased_at DESC")
          end
          @purchased_day_collection = Order.restaurants_join(@user_restaurants_ids).day_collection(@month, @year).order("purchased_at_day ASC")
        end
        @purchased_month_collection = Order.restaurants_join(@user_restaurants_ids).month_collection(@year).order("purchased_at_month ASC")
      end
      @order_months = @orders.group_by { |o| o.cart.purchased_at.beginning_of_month }
    else
      redirect_to root_path
      return
    end
    respond_to do |format|
      format.html
      format.pdf
      format.xml  { render :xml => @orders}
      format.csv { render :csv => @orders}
    end
  end

  def incomplete_orders
    @orders = Order.joins(:cart).where("carts.purchased_at IS NULL OR status NOT IN (?, ?)", "confirmed", "delivering").readonly(false)
  end

  def complete_orders
    @orders = Order.joins(:cart).purchased.where(:status => ["confirmed", "delivering"]).order("carts.purchased_at DESC")
  end

  def update_status
    @order = Order.find(params[:id])
    @order_status_collection = [
      ["placed", "placed"],
      ["unconfirmed", "unconfirmed"],
      ["confirmed", "confirmed"],
      ["delivering", "delivering"]
    ]
    @location = Location.find(@order.location.id)
    @delivery_drivers_array = @location.delivery_drivers.map { |dd| dd.id }
    @delivery_drivers = DeliveryDriver.where(:id => @delivery_drivers_array)
  end

  def update
    @order = Order.find(params[:id])

    if @order.update_attributes(params[:order])
      redirect_to admin_order_path, :notice => "Order status updated."
    else
      redirect_to admin_update_order_status_path(@orders), :alert => "Order status update failed."
    end
  end

  def restaurant_index
    @restaurant = Restaurant.find(params[:restaurant]).name
    if current_user.role?(:admin) || current_user.role?(:restaurant_owner) || current_user.role?(:restaurant_editor)
      @restaurant_collection = Order.restaurant_collection(@month, @year).uniq
      @purchased_collection = Order.year_collection(@restaurant).order("purchased_at_year ASC")
      unless @year == "all"
        @purchased_month_collection = Order.month_collection(@year, @restaurant).order("purchased_at_month ASC")
        unless @month == "all"
          @purchased_day_collection = Order.day_collection(@month, @year, @restaurant).order("purchased_at_day ASC")
        end
      end
      @orders = Order.purchased_at_restaurant(@month, @year, @restaurant).order("carts.purchased_at DESC")
    else
      redirect_to root_path
      return
    end

    respond_to do |format|
      format.html
      format.pdf
      format.xml  { render :xml => @orders}
      format.csv { render :csv => @orders}
    end
  end

  def customer_index
    @customer = Order.find(params[:customer]).email
    if current_user.role?(:admin) || current_user.role?(:restaurant_owner) || current_user.role?(:restaurant_editor)
      @customer_collection = Order.customer_collection(@month, @year).index_by { |r| r[:email] }.values
      @purchased_collection = Order.year_collection(nil, @customer).order("purchased_at_year ASC")
      unless @year == "all"
        @purchased_month_collection = Order.month_collection(@year, nil, @customer).order("purchased_at_month ASC")
        unless @month == "all"
          @purchased_day_collection = Order.day_collection(@month, @year, @restaurant).order("purchased_at_day ASC")
        end
      end
      @orders = Order.purchased_by_customer(@customer, @month, @year).order("carts.purchased_at DESC")
    else
      redirect_to root_path
      return
    end
  end

  def show
    if can? :read, Order
      @order = Order.find(params[:id])
      @first_line_item = @order.cart.line_items.first
    end

    respond_to do |format|
      format.html { render :layout => "order_detail" }
      format.pdf
    end
  end

  private

    def get_params
      @year = params[:year] ? params[:year] : "all"
      @month = params[:month] ? params[:month] : "all"
      @day = params[:day] ? params[:day] : "all"
      @category = params[:category] ? params[:category] : "all"
      @category_collection = {
        :all => "all",
        :restaurant => "restaurant",
        :customer => "customer"
      }
    end

    def sort_column
      #column_names = Order.column_names
      #column_names.push("restaurant_name", "price")
      Order.column_names.include?(params[:sort]) ? params[:sort] : "id"
      #column_names.include?(params[:sort]) ? params[:sort] : "id"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/views/admin/orders/_order_status_form.html.haml
= form_for order, :url => theurl do |f|
  = render "/shared/error_messages", :target => @order
  %fieldset
    %legend
      Order #{@order.id}
    %ol
      %li
        = f.label :status, "Order Status"
        = f.select :status, @order_status_collection
  - if @order.cart.delivers
    %fieldset
      %legend Change Driver
      %ol
        = f.fields_for :cart do |cart_f|
          %li
            = cart_f.label :delivery_driver_id, "Driver"
            = cart_f.select :delivery_driver_id, @delivery_drivers.map {|dd| [dd.user.email, dd.id]}
  %fieldset
    %p= f.submit @submit_name

app/views/admin/orders/complete_orders.html.haml
%h1 Complete Orders
- if @orders && @orders.length > 0
  %table
    %tr
      %th ID
      %th{:align => "left"} Status
      %th{:align => "left"} Purchased At
      %th{:align => "left"} Restaurant
      %th{:align => "left"} Customer
      %th{:align => "right"} Total
      %th &nbsp;
    - @orders.each do |order|
      %tr
        %td{:align => "center"} #{order.id}
        %td #{order.status}
        %td #{order.purchased_at}
        %td #{order.restaurant.name}
        %td #{order.email}
        %td{:align => "right"} #{number_to_currency(order.grand_total)}
        %td #{link_to "Edit", admin_update_order_status_path(order.id)}
- else
  %p.no_records No records.

app/views/admin/orders/customer_index.csv.erb
<%=h customer_csv_string(@orders) %>

app/views/admin/orders/customer_index.html.haml
= h render :partial => "admin/orders/partials/for_header"
%h1 Previous orders
- if @orders && @orders.length > 0
  #view_by_inputs
    = h render :partial => "admin/orders/partials/indexes_select_boxes/year_month_category"
    %p{:style => "width: 50%;"}
      = h label :order, :customer, "Customer"
      = h collection_select(:order, :customer, @customer_collection, :id, :email, :prompt => "all", :selected => params[:customer])
  %p.downloads
    Download: #{h link_to "CSV", admin_orders_by_customer_path(@year, @month, @day, params[:customer], :format => :csv)} | #{h link_to "PDF", admin_orders_by_customer_path(@year, @month, @day, params[:customer], :format => :pdf)}
  = h render :partial => "admin/orders/partials/sums"
  %table
    %tr
      %th.id_col ID
      %th{:align => "left"} Restaurant
      %th.date_col{:align => "left"} Day/Time
      %th.price{:align => "right"} Total
    - @orders.each do |order|
      %tr{:id => "order_#{h order.id}"}
        %td.id_col{:align => "center"}= h link_to order.id, admin_order_path(order.id), :class => "overlay_trigger"
        %td= h link_to truncate(order.restaurant_name, :length => 50), admin_orders_by_restaurant_path(order.purchased_at.year, order.purchased_at.month, order.purchased_at.day, Restaurant.find_by_name(order.restaurant_name).id)
        %td.date_col= h order.purchased_at.strftime("%Y %b %a %l:%M%p %Z")
        %td.price{:align => "right"}= h number_to_currency(order.price)
- else
  %p You have no previous orders on record.

app/views/admin/orders/incomplete_orders.html.haml
%h1 Incomplete Orders
- if @orders && @orders.length > 0
  %table
    %tr
      %th ID
      %th{:align => "left"} Status
      %th{:align => "left"} Purchased
      %th{:align => "left"} Restaurant
      %th{:align => "left"} Customer
      %th{:align => "right"} Total
      %th &nbsp;
    - @orders.each do |order|
      %tr
        %td{:align => "center"} #{order.id}
        %td #{order.status}
        %td #{order.purchased_at ? order.purchased_at : "Not Purchased"}
        %td #{order.restaurant.name}
        %td #{order.email}
        %td{:align => "right"} #{number_to_currency(order.grand_total)}
        %td #{link_to "Update Status", admin_update_order_status_path(order.id)}
- else
  %p.no_records No records.

app/views/admin/orders/index.csv.erb
<%=h csv_string(@orders) %>

app/views/admin/orders/index.html.haml
= render :partial => "admin/orders/partials/for_header"
%p #{link_to "Incomplete Orders", admin_incomplete_orders_path} | #{link_to "Complete Orders", admin_complete_orders_path}
%h1 Previous orders
#view_by_inputs
  = render :partial => "admin/orders/partials/indexes_select_boxes/year_month_category"
- if @orders && @orders.count > 0
  %p.downloads
    Download: #{link_to "CSV", admin_view_orders_path(@year, @month, @day, @category, :format => :csv)} | #{link_to "PDF", admin_view_orders_path(@year, @month, @day, @category, :format => :pdf)}
  = render :partial => "admin/orders/partials/sums"
  %table
    %tr
      - case @category
      - when "restaurant", "customer"
        %th{:align => "left"}
          = (@category == "restaurant") ? "Restaurant" : "Customer"
          /
        %th.count_col #
        %th.price{:align => "right"} Avg
        %th.price{:align => "right"} Total
      - else
        %th.id_col ID
        %th{:align => "left"} Restaurant
        %th.customer_col{:align => "left"} Customer
        %th.date_col{:align => "left"} Day/Time
        %th.price{:align => "right"} Total
        %th &nbsp;
    - @order_months.each do |month, orders|
      - if @category == "restaurant"
        = render :partial => "admin/orders/partials/lists/by_restaurant", :locals => { :orders => orders, :month => month }
      - elsif @category == "customer"
        = render :partial => "admin/orders/partials/lists/by_customer", :locals => { :orders => orders, :month => month }
      - else
        = render :partial => "admin/orders/partials/lists/by_all", :locals => { :orders => orders }
- else
  %p.no_records= no_records

app/views/admin/orders/restaurant_index.csv.erb
<%=h restaurant_csv_string(@orders) %>

app/views/admin/orders/restaurant_index.html.haml
= h render :partial => "admin/orders/partials/for_header"
%h1 Previous orders
- if @orders && @orders.length > 0
  #view_by_inputs
    = h render :partial => "admin/orders/partials/indexes_select_boxes/year_month_category"
    %p
      = h label :order, :restaurant, "Restaurant"
      = h collection_select(:order, :restaurant, @restaurant_collection, :id, :name, :prompt => "all", :selected => params[:restaurant])
  %p.downloads
    Download: #{h link_to "CSV", admin_orders_by_restaurant_path(@year, @month, @day, params[:restaurant], :format => :csv)} | #{h link_to "PDF", admin_orders_by_restaurant_path(@year, @month, @day, params[:restaurant], :format => :pdf)}
  = h render :partial => "admin/orders/partials/sums"
  %table
    %tr
      %th.id_col ID
      %th{:align => "left"} Customer
      %th.date_col{:align => "left"} Day/Time
      %th.price{:align => "right"} Total
    - @orders.each do |order|
      %tr{:id => "order_#{h order.id}"}
        / <td align="center" class="actions one"></haml:block><haml:silent></haml:silent><haml:block></td>
        %td.id_col{:align => "center"}= h link_to order.id, admin_order_path(order.id), :class => "overlay_trigger"
        %td= h link_to truncate(order.email, :length => 50), admin_orders_by_customer_path(order.purchased_at.year, order.purchased_at.month, order.purchased_at.day, order.id)
        %td.date_col= h order.purchased_at.strftime("%Y %b %a %l:%M%p %Z")
        %td.price{:align => "right"}= h number_to_currency(order.price)
- else
  %p You have no previous orders on record.

app/views/admin/orders/show.csv.erb
<%=h show_csv_string(@order) %>

app/views/admin/orders/show.html.haml
= render :partial => "admin/orders/partials/for_header"
- if @order
  %h1
    Order #{@order.id}
  %ul
    %li
      %b Customer:
      #{@order.email}
    %li
      %b Placed:
      #{@order.created_at.strftime('%a, %d %b %Y %I:%S%p %Z')}
    %li
      %b Restaurant:
      #{@order.restaurant_name}
    - if @order.location_address
      %li
        %b Location:
        #{@order.location_address}
    %li
      %p
        Download: #{link_to "PDF", admin_order_path(@order.id, :format => :pdf)} | #{link_to "Print", admin_order_path(@order.id)}
    %li
      %table
        %tr
          %th{:align => "left"} Item
          %th.price{:align => "right"} Price
        - @order.cart.line_items.each do |line_item|
          %tr
            %td
              #{line_item.name}
              <br />
              - if line_item.line_item_options && line_item.line_item_options.count > 0
                Options:
                %ul
                  - line_item.line_item_options.each do |lio|
                    %li #{lio.qty} #{lio.menu_item_option.name}
            %td.price{:align => "right"} #{number_to_currency(line_item_total(line_item))}
          - if line_item.instructions
            %tr
              %td{:colspan => "2"} #{line_item.instructions}
    %li{:style => "text-align: right;"}
      %b Sub Total:
      #{number_to_currency(sub_total(@order))}
    %li{:style => "text-align: right;"}
      %b Tax:
      #{number_to_currency(tax(@order))}
    - if @order.cart.delivers && @order.cart.tip
      %li{:style => "text-align: right;"}
        %b Tip:
        #{number_to_currency(tip(@order))}
    %li{:style => "text-align: right;"}
      %b Grand Total:
      #{number_to_currency(total(@order))}
  - if @order.cart.delivers
    %p
      #{@order.billing_address.first_name} #{@order.billing_address.last_name} at #{@order.deliver_address}
- else
  %p
    No order exists with id #{params[:id]}

app/views/admin/orders/update_status.html.haml
%h1 Update Order #{@order.id}
= render :partial => "order_status_form", :locals => {:order => @order, :theurl => admin_order_path(@order, :method => "put"), :submit_name => "Update status"}